name: facesbyplaces
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_bloc: ^6.1.1
  image_picker: ^0.6.7+22
  material_design_icons_flutter: ^4.0.5855
  camera: ^0.7.0+1
  shared_preferences: ^0.5.12+4
  dio: ^3.0.10
  date_time_picker: ^1.1.1
  video_player: ^1.0.1
  reorderables: ^0.3.2
  pinput: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  loader_overlay: ^1.1.1
  intl_phone_number_input: ^0.6.0
  async: ^2.4.2
  pull_to_refresh: ^1.6.3
  network_to_file_image: ^2.3.8
  path_provider: ^1.6.27
  cached_network_image: ^2.5.0
  extended_image: ^1.5.0
  location: ^3.2.4
  geocoding: ^1.0.5
  google_sign_in: ^4.5.9
  sign_in_with_apple: ^2.5.4
  firebase: ^8.0.0
  flutter_signin_button: ^1.1.0
  flutter_login_facebook: ^0.4.2+3
  clipboard: ^0.1.2+8
  flutter_staggered_grid_view: ^0.3.3
  timeago: ^2.0.29
  modal_bottom_sheet: ^1.0.0+1
  font_awesome_flutter: ^8.11.0
  badges: ^1.1.6
  date_time_format: ^1.1.1+1
  full_screen_menu: ^0.1.3
  carousel_slider: ^3.0.0
  flutter_branch_sdk: ^1.3.3
  maps: ^0.4.3
  qr_flutter: ^3.2.0
  share: ^0.6.5+4
  stripe_payment: ^1.0.10
  flutter_barcode_scanner: ^1.0.2
  mime: ^0.9.7
  giffy_dialog: ^1.8.0
  overlay_support: ^1.0.5
  firebase_messaging: ^7.0.3
  responsive_framework: ^0.0.14
  flutter_screenutil: ^4.0.3
  sliding_up_panel: ^1.0.2
  keyboard_attachable: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
